# Generated by Django 5.1 on 2024-08-15 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0003_account_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="accounts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True),
        ),
    ]
