# Generated by Django 5.1 on 2024-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0004_alter_account_users_alter_user_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(max_length=100)),
            ],
        ),
    ]
