# Generated by Django 5.1 on 2024-08-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_rename_plant_tree_rename_plant_plantedtree_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='location',
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
